services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nekoziman_development
      POSTGRES_USER: nekoziman
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: ./backend
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://nekoziman:password@db:5432/nekoziman_development
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - bundle_cache:/usr/local/bundle
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  bundle_cache:
